{% set version = "2.0.1" %}

package:
  name: allennlp-models
  version: {{ version }}

source:
  url: https://github.com/allenai/allennlp-models/archive/v{{ version }}.tar.gz
  sha256: 1fbf71af372172ef041afaccc402b8030b9ec9ef131b6fd0c67eb9af5ef1d131

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not linux]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - allennlp =={{ version }}
    - conllu ==4.2.2
    - ftfy
    - nltk
    - py-rouge ==1.1
    - pytorch >=1.7.0,<1.8
    - word2number >=1.1

test:
  requires:
    - pytest
    - flaky
    - spacy-model-en_core_web_sm
  source_files:
    - tests/
    - test_fixtures/
  imports:
    - allennlp_models
  commands:
    # from upstream: https://github.com/allenai/allennlp-models/blob/main/Makefile
    - pytest --color=yes -rf -m "not pretrained_model_test and not pretrained_config_test"

about:
  home: https://github.com/allenai/allennlp-models
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Officially supported AllenNLP models

  doc_url: https://docs.allennlp.org/models/stable/
  dev_url: https://github.com/allenai/allennlp-models

extra:
  recipe-maintainers:
    - h-vetinari
